### ISSUE TITLE
problems with ulmo and pandas version

### ISSUE THREAD

**Issue by emiliom** [waterhackweek/tsdata_access#1]
Posted by @YifanCheng via email:

I currently encountered some problems concerning ulmo and pandas. First, the most recent published ulmo is 0.8.4 (the most updated one I can download from conda-forge), which is already two years old. This package is not compatible with the most updated pandas (0.24.0), mainly including the following two problems. 
- pandas.tslib is deprecated in 0.24.0 but still used in 0.23.4 (ulmo cannot properly imported if I use 0.24.0)
- pandas.to_datetime is deprecated at 0.21.1, instead using pandas.to_pydatetime (I cannot specify the start and end date in ulmo.usgs.nwis.get_site_date())

Thus I chose to use pandas 0.23.4 and manually change the code in ulmo package (lib/python3.6/site-packages/ulmo/util/misc.py), Line 52 from: "return pandas.Timestamp(datetime).to_datetime()" to "return pandas.Timestamp(datetime).to_pydatetime()", which works fine for now. Or we can manually pull the newer version from github repo, which I am not sure how hard it would be for beginners.  

If you have better solutions or suggestions, please let me know.

**Comment by emiliom** [comment]
For my reference:
- https://github.com/ulmo-dev/ulmo/issues/156
  - https://github.com/ulmo-dev/ulmo/blob/master/ulmo/util/misc.py#L52
- https://github.com/ulmo-dev/ulmo/issues/160 and https://github.com/ulmo-dev/ulmo/pull/157

And unrelated ulmo fixes we may want, currently listed as open PR's:
- https://github.com/ulmo-dev/ulmo/pull/165
- https://github.com/ulmo-dev/ulmo/pull/164

**Comment by emiliom** [comment]
@YifanCheng I think I've got an ulmo version that should fix all the problems.

Download the environment.yml file from this repo: https://github.com/waterhackweek/tsdata_access/blob/master/environment.yml
Enable miniconda, on the shell. Then, on the shell, from the directory where you downloaded the environment file, do this: `conda env create -f environment.yml`. That will create a conda environment called "whwtimeseries" that uses pandas 0.24.

Give it a try and let me know how it goes. I'll try it this weekend, too.

**Comment by YifanCheng** [comment]
@emiliom I just tried and it worked fine for what I have been done! Thanks!
